### ISSUE TITLE
Installation fails with "Invalid comparison operator in dependency: >="

### ISSUE THREAD

**Issue by t-tte** [xnie/rlearner#1]
I was looking into this interesting method and came across the following issue when attempting to install the package.

Running the suggested installation method

```
library(devtools)
devtools::install_github("xnie/rlearner")
```

results in the following error:

```
Downloading GitHub repo xnie/rlearner@master
Show Traceback
Error in FUN(X[[i]], ...) : Invalid comparison operator in dependency: >=
```

Some of the solutions suggested elsewhere to similar problems, such as installing the dependencies separately and loading the latest version of devtools, don't seem to work.

For example, running the script below produces the same error:

```
install.packages(c("devtools", "splines", "stats", "Rlab", "glmnet", "magrittr", "caret", "zeallot", "dplyr", "tidyr", "purrr", "xgboost", "rBayesianOptimization", "parallel", "stringr"))
library(devtools)
devtools::install_github("hadley/devtools")
devtools::install_github("xnie/rlearner")
```

I replicated this in two different machines.

**Comment by alejandroschuler** [comment]
I poked around and it seems some people were having this issue in other packages due to trailing whitespace so I made a small change to the DESCRIPTION file to address that. See if it works now and if not we'll have to look into it further...

**Comment by t-tte** [comment]
Thanks for looking into this. It seems like there are still some rogue whitespaces. If I run:
```
library(devtools)
install_github("xnie/rlearner")
```
It fails with the following:
```
─  preparing ‘rlearner’:
E  checking DESCRIPTION meta-information ...
   Malformed Authors@R field:
     <text>:6:0: unexpected end of input
   4:   person("Alejandro", "Schuler", email = "aschuler@stanford.edu", role = "aut"),
   5:   person("Stefan", "Wager", email = "swager@stanford.edu", role = "aut")
     ^
   
   See section 'The DESCRIPTION file' in the 'Writing R Extensions'
   manual.
   
Error in run(bin, args = real_cmdargs, stdout_line_callback = real_callback(stdout),  : 
  System command error
```

**Comment by alejandroschuler** [comment]
Alright, I've managed to replicate the problem and I think I've fixed it (by removing whitespace again).... have another go at installing and let me know if it works for you now.

**Comment by t-tte** [comment]
All good now - I was able to install the package and replicate the minimal example. Thanks for the quick fix!
